wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dropout_rate:
  value: 0.2071462796704548
epochs:
  value: 10
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 1.9280016575669424e-05
optimizer:
  value: rmsprop
