wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dropout_rate:
  value: 0.3814679143045626
epochs:
  value: 10
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 64
learning_rate:
  value: 6.564786976312116e-05
optimizer:
  value: rmsprop
