wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dropout_rate:
  value: 0.3890252258425918
epochs:
  value: 40
hidden_layer_1_size:
  value: 32
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 0.005581949968848267
optimizer:
  value: sgd
