wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dropout_rate:
  value: 0.24501089144170388
epochs:
  value: 20
hidden_layer_1_size:
  value: 32
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 5.923852479363731e-05
optimizer:
  value: rmsprop
