wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dropout_rate:
  value: 0.3205955352205472
epochs:
  value: 20
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 64
learning_rate:
  value: 0.00033084258552346107
optimizer:
  value: rmsprop
