wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dropout_rate:
  value: 0.40797231082716146
epochs:
  value: 30
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 5.117118008834225e-05
optimizer:
  value: adam
