wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dropout_rate:
  value: 0.4531783918595841
epochs:
  value: 20
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 0.00020573014924653345
optimizer:
  value: rmsprop
