wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
dropout_rate:
  value: 0.3426686604887168
epochs:
  value: 20
hidden_layer_1_size:
  value: 32
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 6.698134198923565e-05
optimizer:
  value: adam
