wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dropout_rate:
  value: 0.22047020949067353
epochs:
  value: 40
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.0008475545422625036
optimizer:
  value: sgd
