wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dropout_rate:
  value: 0.1586913924891794
epochs:
  value: 20
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 64
learning_rate:
  value: 0.00151924483051099
optimizer:
  value: sgd
