wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dropout_rate:
  value: 0.25979974313066645
epochs:
  value: 10
hidden_layer_1_size:
  value: 32
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.0017904213788159167
optimizer:
  value: sgd
