wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
dropout_rate:
  value: 0.33261386622820965
epochs:
  value: 30
hidden_layer_1_size:
  value: 32
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 0.004939561794461328
optimizer:
  value: adam
