wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dropout_rate:
  value: 0.35766477904360117
epochs:
  value: 20
hidden_layer_1_size:
  value: 32
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.00036811323626688934
optimizer:
  value: adam
