wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dropout_rate:
  value: 0.16671936453656136
epochs:
  value: 40
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 6.658487862578759e-05
optimizer:
  value: sgd
