wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dropout_rate:
  value: 0.27629065566123856
epochs:
  value: 10
hidden_layer_1_size:
  value: 32
hidden_layer_2_size:
  value: 64
learning_rate:
  value: 7.587687778744316e-05
optimizer:
  value: rmsprop
