wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dropout_rate:
  value: 0.47431158223520087
epochs:
  value: 20
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 1.3264781500742428e-05
optimizer:
  value: adam
