wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dropout_rate:
  value: 0.41045579562237344
epochs:
  value: 20
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 3.74720102419512e-05
optimizer:
  value: sgd
