wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dropout_rate:
  value: 0.48300532993749246
epochs:
  value: 30
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 0.00021307865758587416
optimizer:
  value: rmsprop
