wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dropout_rate:
  value: 0.19231273146040573
epochs:
  value: 40
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.00183050677162764
optimizer:
  value: adam
