wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
dropout_rate:
  value: 0.4262992520207207
epochs:
  value: 20
hidden_layer_1_size:
  value: 32
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.006456680267250961
optimizer:
  value: rmsprop
