wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dropout_rate:
  value: 0.39301707193583835
epochs:
  value: 40
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 64
learning_rate:
  value: 1.3541856124497065e-05
optimizer:
  value: adam
