wandb_version: 1

activation:
  value: relu
batch_size:
  value: 32
dropout_rate:
  value: 0.25059930221609206
epochs:
  value: 30
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.00031567272317003554
optimizer:
  value: adam
