wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dropout_rate:
  value: 0.4042503143109951
epochs:
  value: 20
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.006878327488363454
optimizer:
  value: adam
