wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dropout_rate:
  value: 0.3920960744859331
epochs:
  value: 10
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 0.000373524298729864
optimizer:
  value: sgd
