wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dropout_rate:
  value: 0.30041602780181
epochs:
  value: 10
hidden_layer_1_size:
  value: 32
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.0012946190826384203
optimizer:
  value: rmsprop
