wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dropout_rate:
  value: 0.2684484170985765
epochs:
  value: 10
hidden_layer_1_size:
  value: 32
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 0.0004319577033175728
optimizer:
  value: sgd
