wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dropout_rate:
  value: 0.28244981128416347
epochs:
  value: 10
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.0007725328620496533
optimizer:
  value: rmsprop
