wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dropout_rate:
  value: 0.2552411609774119
epochs:
  value: 30
hidden_layer_1_size:
  value: 32
hidden_layer_2_size:
  value: 64
learning_rate:
  value: 2.2348573012625552e-05
optimizer:
  value: adam
