wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 128
dropout_rate:
  value: 0.4319615451383899
epochs:
  value: 20
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.0003762830754929933
optimizer:
  value: adam
