wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dropout_rate:
  value: 0.1459624000888074
epochs:
  value: 40
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 0.0015071416039091749
optimizer:
  value: rmsprop
