wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dropout_rate:
  value: 0.3379235994998261
epochs:
  value: 40
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.004036243696488913
optimizer:
  value: rmsprop
