wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dropout_rate:
  value: 0.33602674556370893
epochs:
  value: 10
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.008425371810678857
optimizer:
  value: sgd
