wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dropout_rate:
  value: 0.41797831433920785
epochs:
  value: 30
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 2.1619678038715652e-05
optimizer:
  value: rmsprop
