wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dropout_rate:
  value: 0.13814605865039675
epochs:
  value: 40
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 5.9703435209582986e-05
optimizer:
  value: sgd
