wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 64
dropout_rate:
  value: 0.17273784749202714
epochs:
  value: 10
hidden_layer_1_size:
  value: 32
hidden_layer_2_size:
  value: 16
learning_rate:
  value: 0.0027429497701733957
optimizer:
  value: rmsprop
