wandb_version: 1

activation:
  value: relu
batch_size:
  value: 128
dropout_rate:
  value: 0.4440460969984489
epochs:
  value: 20
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 0.004168393098203221
optimizer:
  value: adam
