wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dropout_rate:
  value: 0.44789080248894486
epochs:
  value: 30
hidden_layer_1_size:
  value: 64
hidden_layer_2_size:
  value: 64
learning_rate:
  value: 0.0007653900315896943
optimizer:
  value: adam
