wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dropout_rate:
  value: 0.19544143874139408
epochs:
  value: 20
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 64
learning_rate:
  value: 3.98906607360202e-05
optimizer:
  value: adam
