wandb_version: 1

activation:
  value: tanh
batch_size:
  value: 32
dropout_rate:
  value: 0.1704768744344617
epochs:
  value: 30
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 0.0017673364233396144
optimizer:
  value: sgd
