wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
dropout_rate:
  value: 0.40344465196540025
epochs:
  value: 20
hidden_layer_1_size:
  value: 128
hidden_layer_2_size:
  value: 32
learning_rate:
  value: 0.00823265702867493
optimizer:
  value: rmsprop
